### Accepted scientific articles

7 accepted scientific articles

1. **Vieilledent G., C. Grinand, F. A. Rakotomalala, R. Ranaivosoa, J.-R. Rakotoarijaona, T. F. Allnutt, and F. Achard.** 2018. Combining global tree cover loss data with historical national forest-cover maps to look at six decades of deforestation and forest fragmentation in Madagascar. _Biological Conservation_. 222: 189-197. [doi:10.1016/j.biocon.2018.04.008].
2. **Grinand C., G. Le Maire, G. Vieilledent, H. Razakamanarivo, T. Razafimbelo, and M. Bernoux.** 2017. Estimating temporal changes in soil carbon stocks at the ecoregional scale in Madagascar using remote-sensing. _International Journal of Applied Earth Observation and Geoinformation_. 54: 1-14. [doi:10.1016/j.jag.2016.09.002].
3. **Dezécache C., J.-M. Salles, G. Vieilledent, and B. Hérault.** 2017. Moving forward socio-economically focused models of deforestation. _Global Change Biology_. 23(9): 3484-3500. [doi:10.1111/gcb.13611].
4. **El Hajj M., N. Baghdadi, I. Fayad, G. Vieilledent, J.-S. Bailly, and D. Ho Tong Minh.** 2017. Interest of integrating spaceborne LiDAR data to improve the estimation of biomass in high biomass forested areas. _Remote Sensing_. 9(3). [doi:10.3390/rs9030213].
5. **Vieilledent G., O. Gardi, C. Grinand, C. Burren, M. Andriamanjato, C. Camara, C. J. Gardner, L. Glass, A. Rasolohery, H. Rakoto Ratsimba, V. Gond, J.-R. Rakotoarijaona.** 2016. Bioclimatic envelope models predict a decrease in tropical forest carbon stocks with climate change in Madagascar. _Journal of Ecology_. 104: 703-715. [doi:10.1111/1365-2745.12548].
6. **Vancutsem Ch., F. Achard, J.-F. Pekel, G. Vieilledent, S. Carboni, D. Simonetti, J. Gallego.** Pantropical analysis of the Landsat archive reveals unprecedented deforestation rates in evergreen forests. _Science Advances_. in press.
7. **Grinand C., G. Vieilledent, T. Razafimbelo, J.-R. Rakotoarijaona, M. Bernoux.** 2020. Modelling and forecasting deforestation, land degradation and regeneration in Madagascar using machine learning tools and a global land cover change dataset. _Land Degradation and Development_.

### Submitted scientific articles

4 submitted scientific articles

1. **Vieilledent G.** ForestAtRisk: A Python package for modelling and forecasting deforestation in the tropics. _Journal of Open Source Software_. Submitted. 
2. **Vieilledent G., C. Grinand, M. Pedrono, T. Rabetrano, J.-R. Rakotoarijaona, B. Rakotoarivelo, F. A. Rakotomalala, L. Rakotomalala, A. Razafimpahanana and F. Achard.** It's not only poverty: global trade and bad governance are responsible for the unceasing deforestation in western Madagascar. _Conservation Letters_. Submitted.
3. **Muniz-Tagliari M., P. Danthu, J.-M. Leong Pock-Tsy, C. Cornu, J. Lenoir, V. Carvalho-Rocha, G. Vieilledent.** Not all species will migrate poleward as the climate warms: the case of the seven baobab species in Madagascar. _Ecography_. Submitted.
4. **Vieilledent G., Ch. Vancutsem and F. Achard.** Spatial forecasting of forest cover change in the humid tropics over the 21 st century. _Science_. Submitted.

### Scientific articles in preparation

6 articles in preparation

1. **Charra M., S. Goodman, A. Raselimanana, M.-J. Raherilalao, V. Soarimalala, D. Lees, F. Rakotondrainibe, J. Moat, M. Andriamanjato, W. J. Baker, M. Rakotoarinivo, M. Vorontsova,T. Pearce, T. F. Allnutt, D. Razafimpahanana, M. Pedrono, J.-R. Rakotoarijaona and G. Vieilledent.** Climate or watersheds ? Environmental factors determining species assemblages change according to the taxonomic group. _Evolution_. In prep.
2. **Clement J., G. Vieilledent.** jSDM: an R package for Joint Species Distribution Modelling. _Ecography_. In prep.
3. **Knoploch C., C. Grinand, G. Vieilledent.** Extinction risk of the Lemurs of Madagascar under both the effect of climate change and deforestation. _Conservation Biology_. In prep.
4. **Vieilledent G., and F. Achard.** Including spatial-autocorrelation in deforestation models to obtain realistic deforestation projections at national or continental scales. _Landscape Ecology_. In prep.
5. **Vieilledent G., W. F. Laurance, S. Peedell and F. Achard.** The fate of tropical forests associated to the demographic explosion in Africa. _Current Biology_. In prep.
6. **Vieilledent G.** MadaClim: a set of climatic and environmental spatial variables for Madagascar. Data paper. _Ecology_. In prep.

